"use client";
import { usePathname } from "next/navigation";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
// import PopUp from "../components/PopUp/PopUp";
// export const metadata = {
//   title: 'CryptQuiz',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body className="relative">
      
        <div className="relative bg-neu-yellow h-[100vh] w-[100vw] flex flex-col items-center justify-center py-8 lg:py-0">
          {/* <PopUp/> */}
        
          <header className="lg:hidden flex flex-row justify-between items-center w-[80vw] h-[4vh] my-4">
          <Link href="/home"> 
            <div>
              <Image
                src="/images/ge2.png"
                alt="profile"
                width={44}
                height={48}
              />  
            </div>
            </Link>
          <Link href="/profile">
            <div>
              <Image
                className="rounded-full border border-black border-r-2 border-b-2"
                src="/images/icardi.jpg"
                alt="profile"
                width={48}
                height={48}
              />
            </div>
            </Link>
          </header>
          {pathName !== "/profile" ? 
            <div className="w-[80vw] h-[85vh] lg:h-[80vh] bg-neu-white rounded-20 lg:rounded-40 overflow-hidden border border-black border-r-4 border-b-4 lg:border-r-8 lg:border-b-8">
              {children}
            </div>
           : <div>
            {children}
            </div>}
          {/* {pathName === "/quiz" || pathName === "/leaderBoard" ? <Sponsor /> : null} */}
        </div>
      </body>
    </html>
  );
}