"use client";
import { usePathname } from "next/navigation";
import "./globals.css";
import Image from "next/image";
import Sponsor from "@/components/sponsor";

// export const metadata = {
//   title: 'CryptQuiz',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathName = usePathname();
  console.log("aq" + pathName);

  return (
    <html lang="en">
      <body className="bg-neu-yellow bg-no-repeat relative">
        {pathName !== "/" ? (
          <div className="bg-neu-yellow min-h-screen flex flex-col justify-center items-center">
            <div className="container w-4/5 bg-neu-white rounded-40 overflow-hidden border border-black border-r-8 border-b-8 h-5/6">
              <div className="absolute top-4 left-64">
                <Image
                  className="drop-shadow-[2px_2px_rgba(0,0,0,40)]"
                  src="/images/ex1.png"
                  alt="images"
                  width={136}
                  height={136}
                />
              </div>
              {pathName === "/quiz" ? (
                <div>
                  <div className="h-4 bg-red-500 w-full rounded-t-40"></div>
                </div>
              ) : null}
              <div className="mt-3 pb-12 flex justify-between">
                {pathName === "/quiz" || pathName === "/description" ? (
                  <div className="flex-none">
                    <Image
                      src="/images/sol.png"
                      alt="images"
                      height={762}
                      width={100}
                    />
                  </div>
                ) : null}

                {children}

                {pathName === "/quiz" || pathName === "/description" ? (
                  <div className="flex-none">
                    <Image
                      src="/images/sag.png"
                      alt="images"
                      height={762}
                      width={100}
                    />
                  </div>
                ) : null}
              </div>
            </div>
            {/* sponsor */}
            {pathName === "/quiz" || pathName === "/leaderBoard" ? <Sponsor /> : null}
          </div>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  );
}
